
site_name: Seguridad en sistemas del curso de especialista en ciberseguridad
site_url: https://raul-profesor.github.io/Curso-especialista-ciberseguridad/


theme:
  name: material
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    
  palette:
      - scheme: default
        primary: light green
        toggle:
          icon: material/toggle-switch-off-outline
          name: Cambiar a modo oscuro
      - scheme: slate
        primary: teal
        toggle:
          icon: material/toggle-switch
          name: Cambiar a modo normal
  plugins:
    - mkdocs-video:
        mark: "vid"
    - search:
      lang: es

      
markdown_extensions: 
  - admonition
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.caret   
  - pymdownx.critic 
  - pymdownx.details 
  - attr_list
  - md_in_html
  - footnotes

nav:
  - Warm up:
    - section/index.md
    - Entornos Linux: section/EntLinux.md
    - Ejercicios propuestos Linux: section/Ej_Linux.md
    - Entornos Windows: section/EntWin.md
    - Ejercicios propuestos Windows: section/Ej_Win.md
    - Webgrafía: section/webgrafia.md
  - Seguridad ofensiva:
    - segof/index.md
    - Introducción: segof/Intro.md
    - Introducción a Nmap: segof/nmap101.md
    - Enumeración de servicios: segof/enumeracion.md
    - Causas de vulnerabilidades en sistemas: segof/servicios_desact.md
    - Explotación de vulnerabilidades: segof/exploit.md
    - Metasploit: segof/metasploit.md
    - Ejercicio práctico - Explotación de EternalBlue: segof/EternalBlue.md
    - Shells: segof/rev_shell.md
    - Escalada de privilegios: segof/privesc.md
    - Enumeración en entornos AD (Active Directory): segof/ad_enumeration.md
    - Gestión y almacenamiento de credenciales en Windows: segof/passw_manag.md
    - Spoofing & phising: segof/phising.md    
    - Ataques en entornos Active Directory: segof/HackingAD1.md
    - Laboratorio de pivoting: segof/Pivoting.md
    - Webgrafía: segof/webgrafia.md
  - Seguridad defensiva:
    - segdef/index.md
    - Análisis de Logs: segdef/logs.md
    - Monitorización con IDS/IPS: segdef/idps.md
    - Hardening SSH: segdef/hardening.ssh.md
    - Monitorización con Security Onion: segdef/seconion.md
    - Monitorización de red con Arkime: segdef/arkime.md
    - Análisis de archivos con TruffleHog: segdef/truffle.md
    - (ACTUALIZADO) Análisis de archivos con TruffleHog: segdef/truffle2.md
    - Análisis de infraestructura (contenedores) con Trivy: segdef/trivy.md
  - Respuesta a incidentes (IR):
    - Introdución a la respuesta a incidentes: IR/intro.md
    - Casos prácticos de respuesta a incidentes: IR/casos.md
    - Detección de web shells con Wazuh: IR/wazuh.md    
    


extra_css:
  - stylesheets/extra.css

extra:
  analytics: 
      provider: google 
      property: G-3NX5MD5C8H

